<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Shop</name>
   <tag></tag>
   <elementGuidId>752ebcac-7cd4-4f34-9609-b9d8aa1873ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ul.menu > li.page_item.page-item-6 > a.ct-menu-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='header-menu-1']/ul/li[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>004b55d4-b33f-44f4-93c4-6ed0afacf03b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://erlangga.enjoyproject.online/shop/</value>
      <webElementGuid>d451f6ec-3a92-410a-961d-93a713629b1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ct-menu-link</value>
      <webElementGuid>b52f0685-10c2-4b5f-b559-e4f050cac936</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Shop</value>
      <webElementGuid>0d10c954-a50d-455f-ae57-11541da57281</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header-menu-1&quot;)/ul[@class=&quot;menu&quot;]/li[@class=&quot;page_item page-item-6&quot;]/a[@class=&quot;ct-menu-link&quot;]</value>
      <webElementGuid>017b7869-ea66-4bef-9c8d-aedcd64e719b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='header-menu-1']/ul/li[4]/a</value>
      <webElementGuid>b577ab51-6c69-4d83-88ad-f5f4a93d773a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Shop')])[2]</value>
      <webElementGuid>7559c893-3d82-404e-a958-c63c7d673603</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Checkout'])[2]/following::a[1]</value>
      <webElementGuid>6765f1a8-ffde-4773-8c74-f702d196ebfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cart'])[2]/following::a[2]</value>
      <webElementGuid>ce6a3441-528d-4aeb-b05c-d24792adddde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/preceding::a[1]</value>
      <webElementGuid>e232a9b4-a590-4906-abbc-94dd26fb017c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menu'])[1]/preceding::a[3]</value>
      <webElementGuid>8e1006e0-8e19-4070-af4c-1f09ec40e008</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://erlangga.enjoyproject.online/shop/')])[2]</value>
      <webElementGuid>670c59cf-ca2b-4ff3-8630-ac647d630f56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/nav/ul/li[4]/a</value>
      <webElementGuid>e6f361d9-9ae8-4374-83f1-f2499f0ac867</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://erlangga.enjoyproject.online/shop/' and (text() = 'Shop' or . = 'Shop')]</value>
      <webElementGuid>79470b46-1edd-4c08-a7ab-ff45201a7101</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
