<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Account</name>
   <tag></tag>
   <elementGuidId>8e57b6ad-89db-4e63-936c-1e664d4b1a7c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ul.menu > li.page_item.page-item-9 > a.ct-menu-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='header-menu-1']/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>50733701-fc8e-4b09-aeb7-a4ab55cb93f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://erlangga.enjoyproject.online/account/</value>
      <webElementGuid>1001efff-95f6-475f-a89d-e38479007779</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ct-menu-link</value>
      <webElementGuid>8de1b49c-da7e-4444-96cc-ff3560fe3b0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Account</value>
      <webElementGuid>3791204e-a412-4cb2-9075-354e3b202ff9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header-menu-1&quot;)/ul[@class=&quot;menu&quot;]/li[@class=&quot;page_item page-item-9&quot;]/a[@class=&quot;ct-menu-link&quot;]</value>
      <webElementGuid>0047577b-6e88-4214-9c19-4a26afe289c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='header-menu-1']/ul/li/a</value>
      <webElementGuid>aec77b72-e169-4a0b-a1b7-5d588e22caa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Account')])[2]</value>
      <webElementGuid>1cd68368-7f0e-4c91-b05a-987bb94acbe4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shop'])[1]/following::a[3]</value>
      <webElementGuid>5c21762b-351b-47aa-8c8b-dceb93f5e1eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Checkout'])[1]/following::a[4]</value>
      <webElementGuid>262574fd-a1b8-4c03-92ed-9d3d895c20fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cart'])[2]/preceding::a[1]</value>
      <webElementGuid>bfafac80-aab2-4410-b300-daf9b8639c89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Checkout'])[2]/preceding::a[2]</value>
      <webElementGuid>713e09e5-8b04-4161-9726-a21452fba86f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://erlangga.enjoyproject.online/account/')])[2]</value>
      <webElementGuid>c82ed79d-4d26-4ec3-ba1c-979c1282a660</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/nav/ul/li/a</value>
      <webElementGuid>81756da9-fdef-4790-8ab6-e4807a304fce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://erlangga.enjoyproject.online/account/' and (text() = 'Account' or . = 'Account')]</value>
      <webElementGuid>e81bdaf6-90bf-4ba9-8632-8724a0d04dc7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
