<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Account</name>
   <tag></tag>
   <elementGuidId>0907ba70-f0e4-4897-824f-e78f7ebf5c50</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ul.menu > li.page_item.page-item-9 > a.ct-menu-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='header-menu-1']/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>55123f88-419a-4a80-80ca-32e8838e84e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://erlangga.enjoyproject.online/account/</value>
      <webElementGuid>a1fa4df3-4c75-4bab-bc65-ec7fd6cd71e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ct-menu-link</value>
      <webElementGuid>23e3fe0d-cac8-4031-9606-c971b1eee3a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Account</value>
      <webElementGuid>2bac3bf2-bf9d-46a5-8138-41b4ef7a32d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header-menu-1&quot;)/ul[@class=&quot;menu&quot;]/li[@class=&quot;page_item page-item-9&quot;]/a[@class=&quot;ct-menu-link&quot;]</value>
      <webElementGuid>cf0cfffb-80a9-48c3-9404-778af7b1187a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='header-menu-1']/ul/li/a</value>
      <webElementGuid>0576cb87-fb9e-40c6-81bb-0937c7ac8bc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Account')])[2]</value>
      <webElementGuid>488bee13-8f58-4b83-9552-42e705dd3696</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shop'])[1]/following::a[3]</value>
      <webElementGuid>225e08f9-3d86-4d2d-9502-6a80ad06b132</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Checkout'])[1]/following::a[4]</value>
      <webElementGuid>79475f22-6f93-48dc-817e-fff3202777d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cart'])[2]/preceding::a[1]</value>
      <webElementGuid>9b3185ea-5a45-40db-bb88-ce088ab776c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Checkout'])[2]/preceding::a[2]</value>
      <webElementGuid>f5420463-fa18-4cee-8e8b-0c03b5c84731</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://erlangga.enjoyproject.online/account/')])[2]</value>
      <webElementGuid>3e883142-8a16-4d68-b0e3-926aa5adbb30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/nav/ul/li/a</value>
      <webElementGuid>24095cf2-d5ed-4807-91dd-50bb20245d1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://erlangga.enjoyproject.online/account/' and (text() = 'Account' or . = 'Account')]</value>
      <webElementGuid>631d3590-14f1-4bc4-bf74-fa7487ee5c9f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
