<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Sepatu Compass Proto Lite Baby Blue</name>
   <tag></tag>
   <elementGuidId>37891a50-806e-41c0-9a4f-647c453e9f56</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.wc-block-components-product-name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='post-7']/div[2]/div/div[4]/div/div/div[2]/table/tbody/tr/td[2]/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ff4d4166-f308-4745-b65d-f8da3e08c80b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wc-block-components-product-name</value>
      <webElementGuid>e9fbeec2-82ea-4d25-9d6f-b5cfccf2af79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://erlangga.enjoyproject.online/product/sepatu-compass%ef%b8%8f-proto-lite-baby-blue/</value>
      <webElementGuid>0094c5a8-046a-4320-b240-37e17df4b282</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sepatu Compass️ Proto Lite Baby Blue</value>
      <webElementGuid>207037d7-38c4-4684-9de8-341cf29a8e5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-7&quot;)/div[@class=&quot;entry-content&quot;]/div[@class=&quot;wp-block-woocommerce-cart alignwide&quot;]/div[4]/div[1]/div[@class=&quot;wc-block-components-sidebar-layout wc-block-cart wp-block-woocommerce-filled-cart-block is-large&quot;]/div[@class=&quot;wc-block-components-main wc-block-cart__main wp-block-woocommerce-cart-items-block&quot;]/table[@class=&quot;wc-block-cart-items wp-block-woocommerce-cart-line-items-block&quot;]/tbody[1]/tr[@class=&quot;wc-block-cart-items__row&quot;]/td[@class=&quot;wc-block-cart-item__product&quot;]/div[@class=&quot;wc-block-cart-item__wrap&quot;]/a[@class=&quot;wc-block-components-product-name&quot;]</value>
      <webElementGuid>c5d808a8-0ef8-472b-af86-74a2bd3e4acf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-7']/div[2]/div/div[4]/div/div/div[2]/table/tbody/tr/td[2]/div/a</value>
      <webElementGuid>d3b5af2f-e3ff-418d-b8c7-ee2fa1002122</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Sepatu Compass️ Proto Lite Baby Blue')]</value>
      <webElementGuid>df7afae1-697b-4587-8fc5-e6852f88a5e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total'])[1]/following::a[2]</value>
      <webElementGuid>1db4d7a6-9db2-4b5c-9c43-45ff79e8cbbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Details'])[1]/following::a[2]</value>
      <webElementGuid>05fe6ac6-16a2-4efc-a94f-4880b4dfa8c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp 578.000,00'])[1]/preceding::a[1]</value>
      <webElementGuid>25fbf78d-6ca2-46a4-a50b-f36029633607</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='－'])[1]/preceding::a[1]</value>
      <webElementGuid>2875aee6-0879-4ab9-b237-f985c7cb01fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sepatu Compass️ Proto Lite Baby Blue']/parent::*</value>
      <webElementGuid>b950287a-dbfa-4615-9ccc-08c81c7bb90c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://erlangga.enjoyproject.online/product/sepatu-compass%ef%b8%8f-proto-lite-baby-blue/')])[2]</value>
      <webElementGuid>9780cb24-6204-4a75-98d9-3fba2928b529</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/a</value>
      <webElementGuid>bd46efc5-c9c8-433b-be76-ade8aa893e4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://erlangga.enjoyproject.online/product/sepatu-compass%ef%b8%8f-proto-lite-baby-blue/' and (text() = 'Sepatu Compass️ Proto Lite Baby Blue' or . = 'Sepatu Compass️ Proto Lite Baby Blue')]</value>
      <webElementGuid>817f6ba6-7b4d-4791-b691-b4407ceb704c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
