<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Cart</name>
   <tag></tag>
   <elementGuidId>f9dad70d-3fcf-4648-b7bf-fd39f2aff7a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ul.menu > li.page_item.page-item-7 > a.ct-menu-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='header-menu-1']/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2cdafda1-5ee3-4423-9db1-0ae50e594d27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://erlangga.enjoyproject.online/cart/?v=637120feeaca</value>
      <webElementGuid>b383b942-daae-40b6-be07-5df37ed6dbd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ct-menu-link</value>
      <webElementGuid>29646b04-974b-4684-ab45-4628647fcdfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cart</value>
      <webElementGuid>3f3df413-f39f-441a-8346-bfa6fabfb42e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header-menu-1&quot;)/ul[@class=&quot;menu&quot;]/li[@class=&quot;page_item page-item-7&quot;]/a[@class=&quot;ct-menu-link&quot;]</value>
      <webElementGuid>9dc36a8c-6029-4364-982b-7cbf74c39cc8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='header-menu-1']/ul/li[2]/a</value>
      <webElementGuid>dbd6c87e-5426-40e8-baa4-aea9203465c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Cart')])[2]</value>
      <webElementGuid>12dfe1b5-2a21-488b-8fcc-4c291d469b38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account'])[2]/following::a[1]</value>
      <webElementGuid>f75eae70-e342-4103-9610-c19d6ef90e8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shop'])[2]/following::a[4]</value>
      <webElementGuid>d696a42a-6e9c-492c-82c8-835673848848</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Checkout'])[2]/preceding::a[1]</value>
      <webElementGuid>3ae6d465-af5f-44ff-8f43-e6d66ac269ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shop'])[3]/preceding::a[2]</value>
      <webElementGuid>2e9631ce-9add-4e1f-83ef-9ea01457b3a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://erlangga.enjoyproject.online/cart/?v=637120feeaca')])[2]</value>
      <webElementGuid>e07282f2-1e6a-4321-8af3-c6d0a810a301</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/nav/ul/li[2]/a</value>
      <webElementGuid>e0522841-962b-4ed3-b35f-14a37f99d5e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://erlangga.enjoyproject.online/cart/?v=637120feeaca' and (text() = 'Cart' or . = 'Cart')]</value>
      <webElementGuid>63343ae2-353b-49c9-aa64-0b254cdbe67f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
