<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Cart</name>
   <tag></tag>
   <elementGuidId>d858dd8c-9d50-4f3f-a15e-b22cde0dcad6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ul.menu > li.page_item.page-item-7 > a.ct-menu-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='header-menu-1']/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>14beaddc-c24e-45ff-8af5-5723ecb68b52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://erlangga.enjoyproject.online/cart/?v=637120feeaca</value>
      <webElementGuid>1f3268c6-d888-4419-b252-503eb1338f96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ct-menu-link</value>
      <webElementGuid>5ae4caee-468b-438d-9565-92c3bc03211d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cart</value>
      <webElementGuid>ddf62c59-60a4-499c-9607-10472fd64512</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header-menu-1&quot;)/ul[@class=&quot;menu&quot;]/li[@class=&quot;page_item page-item-7&quot;]/a[@class=&quot;ct-menu-link&quot;]</value>
      <webElementGuid>cf53b18c-d35d-46e7-ba40-627dcd068bbf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='header-menu-1']/ul/li[2]/a</value>
      <webElementGuid>783a920e-900c-4e1f-be87-d603681a5986</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Cart')])[2]</value>
      <webElementGuid>3aaa6bfb-7501-4766-8561-ef93900dd31b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account'])[2]/following::a[1]</value>
      <webElementGuid>47d12772-2621-4a8f-8da8-b8a89e6fdd20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shop'])[2]/following::a[4]</value>
      <webElementGuid>1d853931-9fd6-447f-8587-2a6b05243edb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Checkout'])[2]/preceding::a[1]</value>
      <webElementGuid>79e9e65e-9157-45b0-a36f-eca9fe50cf58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shop'])[3]/preceding::a[2]</value>
      <webElementGuid>11835c8d-b8d8-4318-ba3d-307f92f9136c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://erlangga.enjoyproject.online/cart/?v=637120feeaca')])[2]</value>
      <webElementGuid>1494940c-530b-49d9-bcf9-efa0c96da1c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/nav/ul/li[2]/a</value>
      <webElementGuid>467f9a80-8d78-4e34-942f-b8f15417babe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://erlangga.enjoyproject.online/cart/?v=637120feeaca' and (text() = 'Cart' or . = 'Cart')]</value>
      <webElementGuid>e9f4acad-02e5-4ae9-9afe-5ad3f44cf278</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
