<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Shop</name>
   <tag></tag>
   <elementGuidId>e48079ef-1ecb-428b-8b2e-7bf4b7c512a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1.page-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main']/div/header/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>6bae1a96-a3fe-4e12-aa4d-b71316836a3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>page-title</value>
      <webElementGuid>7bee5bc0-010f-41f8-8d85-66f9fc9663f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Shop</value>
      <webElementGuid>87c1dee6-42cf-4393-b57c-c996cd90081f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>itemprop</name>
      <type>Main</type>
      <value>headline</value>
      <webElementGuid>0958cbd2-c9ff-4c5a-a371-38c6e7f955d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Shop</value>
      <webElementGuid>9cc771d7-0998-4998-b2eb-e1e4f064b4ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;hero-section&quot;]/header[@class=&quot;entry-header ct-container-narrow&quot;]/h1[@class=&quot;page-title&quot;]</value>
      <webElementGuid>a49e2529-cae7-4890-b625-a0c4066ead07</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div/header/h1</value>
      <webElementGuid>aae9c12e-a5aa-4931-bafa-6790edd00586</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menu'])[1]/following::h1[1]</value>
      <webElementGuid>16e6458c-f892-42fa-aa41-ef17ca494924</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/following::h1[1]</value>
      <webElementGuid>472d6f1a-8372-4dd8-8052-1f0a0691eb9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SALE'])[1]/preceding::h1[1]</value>
      <webElementGuid>a6759ecb-34ac-4b08-b82a-6276ed4893eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hoka One One Kawana 2 Black Running Shoes'])[1]/preceding::h1[1]</value>
      <webElementGuid>c801a63e-2372-4646-a1d9-15fbeb75f890</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>e3102809-e8ec-45f4-bf16-ea8b2d3f3ebf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[@title = 'Shop' and (text() = 'Shop' or . = 'Shop')]</value>
      <webElementGuid>b0ca1dc7-b225-493e-941e-c78cfc182283</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
