<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Shop</name>
   <tag></tag>
   <elementGuidId>ee81cac8-347d-4437-b4a3-1555545f9ded</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1.page-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main']/div/header/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>119d260c-0d82-4871-944c-6ae400b75533</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>page-title</value>
      <webElementGuid>44198023-f61a-4dd3-8d86-49e27c35acb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Shop</value>
      <webElementGuid>70f60212-0b75-43af-b7e6-fbb1b71252c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>itemprop</name>
      <type>Main</type>
      <value>headline</value>
      <webElementGuid>c2b881da-fe53-4e9b-9f60-a1608854bdfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Shop</value>
      <webElementGuid>6cb950f7-ec77-4560-8abc-54b74ce250ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;hero-section&quot;]/header[@class=&quot;entry-header ct-container-narrow&quot;]/h1[@class=&quot;page-title&quot;]</value>
      <webElementGuid>1e605cca-8cce-4b53-9282-fdcea4f96180</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div/header/h1</value>
      <webElementGuid>c53c7954-5378-48f5-ab86-84c99e87d8d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menu'])[1]/following::h1[1]</value>
      <webElementGuid>ad5debfd-34ad-4e90-a883-b1668161c6c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/following::h1[1]</value>
      <webElementGuid>148fd353-9441-4fc1-8129-ed7d5ee0d682</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SALE'])[1]/preceding::h1[1]</value>
      <webElementGuid>4bf47d82-8c8b-4375-b953-9eacab288feb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hoka One One Kawana 2 Black Running Shoes'])[1]/preceding::h1[1]</value>
      <webElementGuid>667fb544-1d1b-4d65-b0c6-dd3a48de7e19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>55e568db-e659-4b1d-8dd9-896e8aca5bb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[@title = 'Shop' and (text() = 'Shop' or . = 'Shop')]</value>
      <webElementGuid>5480cb25-dbc0-4598-a22d-6074af9640ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
